lotatc_inst.options =  {
    -- Generated by LotAtc Configurator
    -- Version :2.2.1
    -- Date    :27.04.2021 07:45:05
    chat_filter = {"^-.*"},
    dedicated_mode = true,
    dedicated_profile = "realistic_persia.lua",
    allowed_users_file = "",
    export_tacview = false,
    enable_debug = false,
    perfs_tests = false,
}
