return {
    name = "advanced-realistic",
    short = "Advanced Realistic",
    locked = true,
    profile_name = "Advanced Realistic - see only what you can really see, no IFF",
    show_datas = false,
    show_sams = false,
    show_weapons = true,
    speed_filter = true,
    relief_filter = true,
    radar = 3,
    ground_radar = 0,
    automatic_type = 3,
    approach_all_airports = 1,
    airport_radar_mode = 2,
    force_player_name = false,
    neutral_coalition_by_default = true,
    use_callsign = 0,
    use_rcs = true,
    use_realtracking = true,
    modelisation = "global",
    tracking_delay = 6,
    use_range_resolution = true,
}
