return {
    name = "arcade",
    short = "Arcade",
    profile_name = "Arcade - see all",
    locked = true,
    show_datas = true,
    show_sams = true,
    show_weapons = true,
    speed_filter = false,
    relief_filter = false,
    radar = 0,
    ground_radar = 0,
    automatic_type = 0,
    approach_all_airports = 2,
    airport_radar_mode = 1,
    force_player_name = true,
    neutral_coalition_by_default = false,
    use_callsign = 1,
    use_rcs = false,
    use_realtracking = false,
    modelisation = "global",
    tracking_delay = 0,
    use_range_resolution = false,
}
