return {
    name = "basic",
    short = "Basic",
    locked = true,
    profile_name = "Basic - see enemy SAM mid/long range",
    show_datas = false,
    show_sams = true,
    show_weapons = true,
    speed_filter = true,
    relief_filter = true,
    radar = 2,
    ground_radar = 0,
    automatic_type = 1,
    approach_all_airports = 1,
    airport_radar_mode = 2,
    force_player_name = true,
    neutral_coalition_by_default = false,
    use_callsign = 1,
    use_rcs = false,
    use_realtracking = false,
    modelisation = "global",
    tracking_delay = 0,
    use_range_resolution = false,
}
