return {
    name = "realistic",
    short = "Realistic",
    locked = true,
    profile_name = "Realistic - see only what you can really see",
    show_datas = false,
    show_sams = false,
    show_weapons = true,
    speed_filter = true,
    relief_filter = true,
    radar = 3,
    ground_radar = 0,
    automatic_type = 1,
    approach_all_airports = 1,
    airport_radar_mode = 2,
    force_player_name = false,
    neutral_coalition_by_default = false,
    use_callsign = 0,
    use_rcs = true,
    use_realtracking = false,
    modelisation = "global",
    tracking_delay = 6,
    use_range_resolution = true,
}
