EAGLECAP = CAPHANDLER:New("USCAP1",6,true)
EAGLECAP:Start()

VIPERCAP = CAPHANDLER:New("USCAP3",6,true) 
VIPERCAP:Start()

HORNETCAP1 = CAPHANDLER:New("USCAP4",6,true )
HORNETCAP1:Start()

FLEETCAP1 = CAPHANDLER:New("USCAP5", 6, true )
FLEETCAP1:Start()
