DSWest = DEEPSTRIKE:New("DS_W","DeepStrikeNorthW","blue")
DSWest:AddTargetStatic("Static Tank 2-1")
DSWest:AddTargetStatic("Static Tank 1-6")
DSWest:AddTargetStatic("Static Ammunition depot-1")
DSWest:AddGDefenseGroupByPrefix("DS_W","red")
DSWest:AddAirDefenceGroup("DS_W_F1")
DSWest:AddAirDefenceGroup("DS_W_F1-1")
DSWest:SetMsg(true,"Blue For has Entered High Security North Western Irani Space, Defence Systems activated.")
DSWest:SetRandomizeGroup(true,50,1000)
DSWest:SetRandomizeUnits(true,20,200)
DSWest:Start()

DSNorth = DEEPSTRIKE:New("DS_N","DeepStrikeNorth","blue")
DSNorth:AddTargetStatic("IranAmmo_1")
DSNorth:AddTargetStatic("Static Warehouse-1")
DSNorth:AddTargetStatic("IranAmmo")
DSNorth:AddTargetStatic("Static Tank 1-1")
DSNorth:AddTargetStatic("Static Tank 1-2")
DSNorth:AddTargetStatic("Static Tank 1-3")
DSNorth:AddTargetStatic("Static Tank 1-4")
DSNorth:AddTargetStatic("Static Tank 1-5")
DSNorth:AddGDefenseGroupByPrefix("DS_N","red")
DSNorth:AddAirDefenceGroup("DS_N_F14_1-1")
DSNorth:AddAirDefenceGroup("DS_N_F14_1")
DSNorth:SetMsg(true,"Blue For has Entered High Security North Irani Space, Defence Systems activated.")
DSNorth:SetRandomizeGroup(true,50,1000)
DSNorth:SetRandomizeUnits(true,20,200)
DSNorth:Start()
