env.info("Persia Aflame Loader")
env.info("Mission by Robert Graham")
env.info("Mission Script Loader Active")
env.info("Loading MOOSE")
dofile(lfs.writedir() .."pg\\scripts\\Moose.lua")
env.info("Loading MIST")
dofile(lfs.writedir() .."pg\\scripts\\mist_4_3_74.lua")

CinCServer.start("139.99.144.189", 3050)
env.info("hHypeMan")
assert(loadfile("C:/HypeMan/HypeMan.lua"))() 
HypeMan.sendBotMessage("Persia Aflame is Starting..... MOOSE,MIST AND CinCServer Already Loaded")
HypeMan.sendBotMessage("Persia Aflame is SRS.lua")
function hm(msg)
	HypeMan.sendBotMessage(msg)
end

dofile(lfs.writedir() .. [[pg\scripts\srs.lua]])
env.info("Loading Peristence")
hm("Persia Aflame CTLD.lua")
dofile(lfs.writedir() .. [[pg\scripts\CTLD.lua]])
hm("Persia Aflame sqns.lua")
dofile(lfs.writedir() .. [[pg\scripts\sqns.lua]])
hm("Persia Aflame airboss.lua")
dofile(lfs.writedir() .. [[pg\scripts\Airboss.lua]])
hm("Persia Aflame ADS.lua")
dofile(lfs.writedir() .. [[pg\scripts\ADS.lua]])
hm("Persia Aflame slothandler1.lua")
dofile(lfs.writedir() .. [[pg\scripts\slothandler1.lua]])
hm("Persia Aflame simple_groupsaving.lua")
dofile(lfs.writedir() .. [[pg\scripts\simple_groupsaving.lua]])
hm("Persia Aflame simple_admingroupsaving.lua")
dofile(lfs.writedir() .. [[pg\scripts\simple_admingroupsaving.lua]])
hm("Persia Aflame simplestaticsaving.lua")
dofile(lfs.writedir() .. [[pg\scripts\simplestaticsaving.lua]])
hm("Persia Aflame simple_scenery_persistence.lua")
dofile(lfs.writedir() .. [[pg\scripts\simple_scenery_persistence.lua]])
hm("Persia Aflame ctld_static_save.lua")
dofile(lfs.writedir() .. [[pg\scripts\ctld_static_save.lua]])
hm("Persia Aflame bluesupportac.lua")
dofile(lfs.writedir() .. [[pg\scripts\bluesupportac.lua]])
hm("Persia Aflame markerevents.lua")
dofile(lfs.writedir() .. [[pg\scripts\markerevents.lua]])
hm("Persia Aflame mission_per.lua")
dofile(lfs.writedir() .. [[pg\scripts\mission_per.lua]])
hm("Persia Aflame ctldsave.lua")
dofile(lfs.writedir() .. [[pg\scripts\ctldsave.lua]])
hm("Persia Aflame manpads.lua")
dofile(lfs.writedir() .. [[pg\scripts\ManPads.lua]])
hm("Persia Aflame intel.lua")
dofile(lfs.writedir() .. [[pg\scripts\intel.lua]])
hm("Persia Aflame dcslink.lua")
dofile(lfs.writedir() .. [[pg\scripts\dcslink.lua]])
hm("Persia Aflame client.lua")
dofile(lfs.writedir() .. [[pg\scripts\client.lua]])
hm("Persia Falme: ALL SCRIPTS LOADED, HAVE A GOOD 8 HRS.")